import random
import requests,os,string
from aiogram.types import  InlineKeyboardMarkup, InlineKeyboardButton
from loader import dp
from aiogram import *
PREFIX = "!/."


@dp.message_handler(commands=['fake'], commands_prefix=PREFIX)
async def igfgnfokc(message: types.Message):
    import requests
    import random
    import string

    URL = "https://random-data-api.com/api/users/random_user"

    response = requests.get(url=URL)

    data = response.json()


    name1 = data["first_name"]
    name2 = data["last_name"]
    email = data["email"]
    dob = data["date_of_birth"]
    zip = data["address"]["zip_code"]
    add1 = data["address"]["street_address"]
    city = data["address"]["city"]
    state = data["address"]["state"]
    co = data["address"]["country"]

    inf = f"""
data generated :)
<b>
Name  = <code> {name1} {name2} </code>
Email = <code>{email}</code>
street = <code>{add1}  </code>
city = <code>{city}</code>
state = <code>{state}</code>
country = <code>{co}</code>
zip code = <code>{zip}</code>
DOB = <code>{dob}</code>

<b>generated by</b> -» <a href="tg://user?id={message.from_user.id}">{message.from_user.first_name}</a>
</b>
  """

    return await message.reply(inf)


























@dp.message_handler(commands=['us'], commands_prefix=PREFIX)
async def igfgnfokc(message: types.Message):

    import requests as r
    # s = r.Session()

    h = {
        'authority': 'randommer.io',
        'method': 'POST',
        'path': '/random-address',
        'scheme': 'https',
        'accept': '*/*',
        'accept-language': 'en-US,en;q=0.9',
        'content-length': '51',
        'content-type': 'application/x-www-form-urlencoded; charset=UTF-8',
        'cookie': 'ezoadgid_232529=-1; ezoref_232529=bing.com; ezosuibasgeneris-1=480921f6-bf96-4e03-660f-f25e86951321; ezoab_232529=mod40-c; active_template::232529=pub_site_mobile.1667732569; ezopvc_232529=1; ezepvv=155; ezovid_232529=400410709; lp_232529=https://randommer.io/random-address; ezovuuidtime_232529=1667732569; ezovuuid_232529=bc7360d7-797b-4ef9-7419-8d96d36c1777; ezds=ffid%3D2%2Cw%3D494%2Ch%3D1021; ezohw=w%3D494%2Ch%3D924; ezux_lpl_232529=1667732574390|2c105d66-37d9-4161-6289-09273b7ae93a|false; __cf_bm=4w0A8fO_1jpPr7bc6_An4MVQZo82Br3fDjnhPfor1oY-1667732573-0-AUWXoOhssxEtagzMUmByZyOqjkl+gqCo7v7SsxHejQQM2YJBhdcMgmMCqzs+1egKMQ==; ezux_ifep_232529=true; ezux_et_232529=73; ezux_tos_232529=171',
        'origin': 'https://randommer.io',
        'user-agent': 'Mozilla/5.0 (Linux; Android 10; POCO F1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Mobile Safari/537.36',
        'x-requested-with': 'XMLHttpRequest',
    }

    url = "https://randommer.io/random-address"
    d = "number=1&culture=en&X-Requested-With=XMLHttpRequest"

    re = r.post(url, data=d, headers=h)
    ret = re.text

    street = ret.split(",")[0]
    street = street[2:]
    apt = ret.split(",")[1]
    apt = apt[1:]
    zip = ret.split(",")[2]
    zip = zip[1:]
    state = ret.split(",")[3]
    state = state[1:]
    city = ret.split(",")[4]
    city = city[1:]
    country = ret.split(",")[5]
    country = country[1:-2]

    inf = f"""
data generated :)
<b>
street = <code>{street}  </code>
city = <code>{city}</code>
state = <code>{state}</code>
country = <code>{country}</code>
zip code = <code>{zip}</code>

<b>generated by</b> -» <a href="tg://user?id={message.from_user.id}">{message.from_user.first_name}</a>
</b>
  """

    return await message.reply(inf)











